2025-09-25 22:37:46,705 - build_data - ERROR - log_error:100 - [TEST_ERROR] This is a test error
2025-09-25 22:37:56,810 - build_data - ERROR - log_error:100 - [INITIALIZATION_ERROR] Failed to initialize pipeline: HTTPSConnectionPool(host='trends.google.com', port=443): Read timed out. (read timeout=10)
2025-09-25 22:37:57,800 - build_data - ERROR - log_error:100 - [UNEXPECTED_ERROR] Unexpected error for term invalid_term_that_does_not_exist: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /sorry/index?continue=https://trends.google.com/trends/api/explore%3Fhl%3Den-US%26tz%3D360%26req%3D%257B%2522comparisonItem%2522%253A%2B%255B%257B%2522keyword%2522%253A%2B%2522invalid_term_that_does_not_exist%2522%252C%2B%2522time%2522%253A%2B%2522today%2B12-m%2522%252C%2B%2522geo%2522%253A%2B%2522%2522%257D%255D%252C%2B%2522category%2522%253A%2B0%252C%2B%2522property%2522%253A%2B%2522%2522%257D&hl=en-US&q=EhAmABcAGXmYALA04crbOrXRGJWV2MYGIi-oRG91Dh3NsvvCfu2tWgemryjs00aFf4dudIdryVMa2I6FRw2uI4Vg2Ak1Xr1BMzICclJaAUM (Caused by ResponseError('too many 429 error responses'))
2025-09-25 22:37:58,648 - build_data - ERROR - log_error:100 - [UNEXPECTED_ERROR] Unexpected error for term valid_term: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /sorry/index?continue=https://trends.google.com/trends/api/explore%3Fhl%3Den-US%26tz%3D360%26req%3D%257B%2522comparisonItem%2522%253A%2B%255B%257B%2522keyword%2522%253A%2B%2522valid_term%2522%252C%2B%2522time%2522%253A%2B%2522today%2B12-m%2522%252C%2B%2522geo%2522%253A%2B%2522%2522%257D%255D%252C%2B%2522category%2522%253A%2B0%252C%2B%2522property%2522%253A%2B%2522%2522%257D&hl=en-US&q=EhAmABcAGXmYALA04crbOrXRGJaV2MYGIi9MurBRuJXTqhrTJOqCgffj8sUoT2teTUqImhDvkwdn6oRY6sHgjG8juPBup8M4ozICclJaAUM (Caused by ResponseError('too many 429 error responses'))
2025-09-25 22:38:11,088 - build_data - ERROR - log_error:100 - [UNEXPECTED_ERROR] Unexpected error for term invalid_term: HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: /sorry/index?continue=https://trends.google.com/trends/api/explore%3Fhl%3Den-US%26tz%3D360%26req%3D%257B%2522comparisonItem%2522%253A%2B%255B%257B%2522keyword%2522%253A%2B%2522invalid_term%2522%252C%2B%2522time%2522%253A%2B%2522today%2B12-m%2522%252C%2B%2522geo%2522%253A%2B%2522%2522%257D%255D%252C%2B%2522category%2522%253A%2B0%252C%2B%2522property%2522%253A%2B%2522%2522%257D&hl=en-US&q=EhAmABcAGXmYALA04crbOrXRGKKV2MYGIi8yOx1Fd7coCwMFCuqZwQv3UudxCo3O2Y0vmrAzh5qjjW-LXiE4_66HE_5TwOFNzDICclJaAUM (Caused by ResponseError('too many 429 error responses'))
2025-09-26 08:10:45,852 - build_data - ERROR - log_error:100 - [TEST_ERROR] This is a test error
2025-09-26 08:11:33,756 - build_data - ERROR - log_error:100 - [CATEGORY_PROCESSING_ERROR] Failed to process category ai-tools: name 'median_volume' is not defined
